version: "3"

services:
  formaptix-server:
    build: "."
    restart: "always"

    environment:
      - DATABASE=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@formaptix-database:5432/${DATABASE_NAME}
      - SECRET=${SECRET}
      - PORT=${PORT}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DISABLE_ADMIN=${DISABLE_ADMIN}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - formaptix-database

  formaptix-database:
    image: "postgres:bullseye"
    restart: "always"

    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - formaptix-database:/var/lib/postgresql/data

volumes:
  formaptix-database: